theme: jekyll-theme-minimal
title: Ｄｏｃｔｒｉｎａｔｉｏｎｗａｖｅ
description: Projeto de webarte comunista.
logo: /sidebar/foxx_9.png
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
exclude: [dev]
